# Copyright (c) IBM Corporation 2020

# IBM collection namespace
namespace: ibm

# Ansible collection for Power HMC
name: power_hmc

# The version of the collection. Must be compatible with semantic versioning
version: 1.4.0

# The path to the Markdown (.md) readme file. This path is relative to the root of the collection
readme: README.md

# A list of the collection's content authors. Can be just the name or in the format 'Full Name <email> (url)
# @nicks:irc/im.site#channel'
authors:
- Anil Vijayan (@AnilVijayan)
- Navinakumar Kandakur (@nkandak1)


### OPTIONAL but strongly recommended

# A short summary description of the collection
description: Ansible Content for IBM Power HMCs - to manage configurations of Power HMC and Power systems managed by the HMC.

# Collection License
license:
- GPL-3.0-only

# Collection Tags
tags: [infrastructure, ibm, power, hmc]

dependencies: {}

# The URL of the originating SCM repository
repository: https://github.com/IBM/ansible-power-hmc

# The URL to any online docs
documentation: https://ibm.github.io/ansible-power-hmc/index.html

# The URL to the homepage of the collection/project
homepage: https://github.com/IBM

# The URL to the collection issue tracker
issues: https://github.com/IBM/ansible-power-hmc/issues

# Files to ignore when building power_hmc collection
build_ignore:
- builds
- devops
- docs/images
- docs/source/demo.rst
- '*.tar.gz'
