---
- name: HMC build management
  hosts: localhost 
  collections: 
      - ibm.power_hmc
  gather_facts: no
  vars:
    curr_hmc_auth:
      username: hscroot
      password: abc123
    hmc_ip: 9.3.147.x

    build_config:
      location_type: nfs
      hostname: 9.3.147.72
      #userid: hmcct
      #passwd: abcd1234
      #sshkey_file: /home/hscroot/private
      mount_location: /HMCImages
      #mount_option: 8
      build_file: /OpenCert/HMC-9-2-OpenCert.iso

  tasks:
  - name: accept new ssh fingerprints
    shell: ssh-keyscan -H {{ hmc_ip }} >> ~/.ssh/known_hosts

  - name: Probe the hmc driver info
    hmc_build_manager:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      state: facts
    register: testout

  - name: Stdout the probed info
    debug:
      msg: '{{ testout }}'

  - name: Update the HMC
    hmc_build_manager:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      build_config: "{{ build_config }}"
      state: updated
    register: testout

  - name: Stdout the probed info
    debug:
      msg: '{{ testout }}'
