- name: demo firmware update
  hosts: hmcs
  connection: local
  collections: ibm.power_hmc
  vars:
    curr_hmc_auth:
      username: '{{ ansible_user }}'
  tasks:
  - name: update managed systems to newer available level found in an sftp repo
    firmware_update:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth: '{{ curr_hmc_auth }}'
      system_name: '{{ item }}'
      repository: sftp
      remote_repo:
        hostname: 9.3.147.210
        userid: <sftpuser>
        passwd: <sftpuserpasswd>
        directory: <images dir>
      level: <level>
      state: updated
    with_items: <systems_to_update>
