---
- name: HMC Password Policy Management Demo
  hosts: hmcs
  connection: local
  collections:
      - ibm.power_hmc
  gather_facts: no
  vars:
      curr_hmc_auth:
          username: hscroot
          password: !vault |
                    $ANSIBLE_VAULT;1.1;AES256
                    37346262613665663138626331643231306436396339643035663730653232323966313662313739
                    3833393733316239646130376665323337623338373530660a663463613764306461386336356565
                    34616135383635373238396537616331623366663036336230616339653262616665383830356239
                    6331613665306432610a653537303262323239366337643462393339616663363963393937623634
                    3337
  
  tasks:
  - name: Create a password policy
    hmc_pwdpolicy:
        hmc_host: '{{ inventory_hostname }}'
        hmc_auth: "{{ curr_hmc_auth }}"
        policy_name: dummy
        policy_config:
            min_pwage: "2"
            pwage: "150"
            min_length: "10"
            hist_size: "9"
            warn_pwage: "10"
            min_digits: "2"
            min_uppercase_chars: "2"
            min_lowercase_chars: "3"
            min_special_chars: "1"
        state: present
    register: testout

  - name: Stdout the created password policy
    debug:
        msg: '{{ testout }}'

  - name: Activate the Password Policy
    hmc_pwdpolicy:
        hmc_host: '{{ inventory_hostname }}'
        hmc_auth: "{{ curr_hmc_auth }}"
        policy_name: dummy
        state: activated
    register: testout

  - name: Stdout the activated password policy
    debug:
        msg: '{{ testout }}'
