- name: Demo HMC upgrade
  hosts: hmcs
  collections:
      - ibm.power_hmc
  connection: local
  gather_facts: no
  vars:
      curr_hmc_auth:
        username: "{{ ansible_user }}"
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  36353734613030613032623330333864326631323135623863303864313033316536316234656138
                  6233643263373837366163336633396338613166633630610a333538393465616235303631383637
                  31376166636238383436393232663066616137373436353631386266333031373332396465376361
                  3133313737353730610a333234613935323432313036363238396530613965383935303936326637
                  3533 
      config:
        location_type: nfs
        hostname: 9.3.147.72
        mount_location: /HMCImages
        build_file: /HMC9.1.910.0/1803052221/x86_64/network_install
  tasks:

  - name: List the HMC current build level
    hmc_update_upgrade:
        hmc_host: '{{ inventory_hostname }}'
        hmc_auth: '{{ curr_hmc_auth }}'
        state: facts
    register: build_info

  - name: Stdout the probed HMC build info
    debug:
      msg: '{{ build_info }}'

  - name: Upgrade the HMC from 870 to 910 using NFS server
    hmc_update_upgrade:
        hmc_host: '{{ inventory_hostname }}'
        hmc_auth: '{{ curr_hmc_auth }}'
        build_config: '{{ config }}'
        state: upgraded
    register: upgraded_hmc_build_info

  - name: Stdout the upgraded Probed HMC build info
    debug:
      msg: '{{ upgraded_hmc_build_info }}'
