---
- hosts: hmcs
  connection: local
     
  tasks:

  - name: Share private key to hmc for passwordless login
    shell:
        cmd: |
            key=`head -n 1 ~/.ssh/id_rsa.pub`
            sshpass -p {{ hmc_password }} ssh  {{ ansible_user }}@{{ inventory_hostname }} mkauthkeys -a "'$key'"
                
