---
- name: HMC Password Policy
  hosts: localhost 
  collections: 
      - ibm.power_hmc
  gather_facts: no
  vars:
    curr_hmc_auth:
      username: hscroot
      password: abc123
    hmc_ip: 9.3.147.x

  tasks:
  - name: accept new ssh fingerprints
    shell: ssh-keyscan -H {{ hmc_ip }} >> ~/.ssh/known_hosts

  - name: Probe the hmc password policy status info
    hmc_pwdpolicy:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      policy_type: status
      state: facts
    register: testout

  - name: Stdout the probed info
    debug:
      msg: '{{ testout }}'

  - name: Create a password policy
    hmc_pwdpolicy:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      policy_name: dummy
      state: present
    register: testout

  - name: Stdout the created password policy
    debug:
      msg: '{{ testout }}'

  - name: Activate the Password Policy
    hmc_pwdpolicy:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      policy_name: dummy
      state: activated
    register: testout

  - name: Stdout the activated password policy
    debug:
      msg: '{{ testout }}'

  - name: Deactivate the password policies
    hmc_pwdpolicy:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      state: deactivated
    register: testout

  - name: Stdout deactivate the password policies
    debug:
      msg: '{{ testout }}'

  - name: Remove a password policy
    hmc_pwdpolicy:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      policy_name: dummy
      state: absent
    register: testout

  - name: Stdout the remove password policy
    debug:
      msg: '{{ testout }}'
  - name: accept new ssh fingerprints
    shell: ssh-keygen -R {{ hmc_ip }}
