---
- name: HMC build management
  hosts: localhost
  collections:
      - ibm.power_hmc
  vars:
    curr_hmc_auth:
      username: '{{ HMC_USER }}'
      password: '{{ HMC_PASSWORD }}'
    hmc_ip: '{{ HMC_IP }}'
    build_config:
      location_type: nfs
      hostname: 9.3.147.72
      mount_location: /HMCImages
      build_file: '{{ file }}'
    build_config1:
      location_type: nfs
      hostname: 9.3.147.72
      mount_location: /HMCImages
      build_file: '{{ file }}'

  tasks:
  - name: accept new ssh fingerprints
    shell: ssh-keyscan -H {{ HMC_IP }} >> ~/.ssh/known_hosts
    tags:
            - sshkey

  - name: Probe the hmc driver info
    hmc_build_manager:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      state: facts
    register: testout
    tags:
         - facts

  - name: HMC Build Info
    debug:
      msg: '{{ testout }}'
    tags:
        - output

  - name: Update the HMC
    hmc_build_manager:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      build_config: "{{ build_config }}"
      state: updated
    register: curr_version
    tags:
        - update

  - name: Update HMC output
    debug:
      msg: '{{ curr_version }}'
    tags:
        - updateoutput

  - name: Upgrade the HMC
    hmc_build_manager:
      hmc_host: '{{ hmc_ip }}'
      hmc_auth: "{{ curr_hmc_auth }}"
      build_config: "{{ build_config1 }}"
      state: upgraded
    register: curr_version
    tags:
         - upgrade

  - name: upgrade HMC Output
    debug:
      msg: '{{ curr_version }}'
    tags:
        - upgradeoutput
